@startuml sequenceDiagramUserStory1

!define MyGreen #009000

skinparam participant {
  BackgroundColor MyGreen
}

Actor User
participant App
participant LoginController
participant MainscreenController
participant PutRecipeController
participant RecipeFilehandler
participant UserFilehandler
participant FileUtil
database recipes.json
database userinfo.json

User -> App: Opens the application
activate App
User -> LoginController: Enters login information
activate LoginController
User -> LoginController: Clicks on: "Login"
LoginController -> MainscreenController: login(ActionEvent event)
deactivate LoginController
activate MainscreenController
User -> MainscreenController: Clicks on: "+ Add Recipe"
MainscreenController -> PutRecipeController: putRecipe(ActionEvent event)
deactivate MainscreenController
activate PutRecipeController
User -> PutRecipeController: Fills in recipe details
User -> PutRecipeController: Clicks on: "Save Recipe"
PutRecipeController -> PutRecipeController: saveRecipe()
PutRecipeController -> RecipeFilehandler: saveRecipeToLibrary()
activate RecipeFilehandler
RecipeFilehandler -> FileUtil: writeRecipe(Recipe recipe)
deactivate RecipeFilehandler
activate FileUtil
FileUtil -> recipes.json: writeFile(Path filePath, T data)
deactivate FileUtil
PutRecipeController -> UserFilehandler: saveRecipeToLibrary()
activate UserFilehandler
UserFilehandler -> FileUtil: writeProfile(Profile profile)
deactivate UserFilehandler
activate FileUtil
FileUtil -> userinfo.json: writeFile(Path filePath, T data)
deactivate FileUtil
User -> PutRecipeController: Clicks on: "Back"
PutRecipeController -> MainscreenController: back(ActionEvent event)
deactivate PutRecipeController
activate MainscreenController
User <-- MainscreenController: Recipe shows in feed
User -> MainscreenController: Clicks on: "Logout"
MainscreenController -> LoginController: logout(ActionEvent event)
deactivate MainscreenController
activate LoginController
User -> App: Closes the application
deactivate LoginController
deactivate App

@enduml