@startuml sequenceDiagramUserStory4

!define MyGreen #009000

skinparam participant {
  BackgroundColor MyGreen
}

Actor User
participant App
participant MainscreenController
participant RecipeController
participant DirectRecipeHubController
participant RecipeFilehandler
participant UserFilehandler
participant Profile
participant FileUtil
database recipes.json
database userinfo.json

activate App
activate MainscreenController
User <-- MainscreenController: Shows all recipes to user
User -> MainscreenController: Clicks on: "Read more" on own recipe
MainscreenController -> RecipeController: showRecipe(ActionEvent event, Recipe recipe)
deactivate MainscreenController
activate RecipeController
User <-- RecipeController: Shows recipe to user
User -> RecipeController: Clicks on trash-icon
RecipeController -> RecipeController: deleteRecipe(MouseEvent event)
User <-- RecipeController: Shows confirmation popup
User -> RecipeController: Clicks on: "OK"
RecipeController -> DirectRecipeHubController: "OK-click"
DirectRecipeHubController -> RecipeFilehandler: removeRecipe(recipe)
RecipeFilehandler -> FileUtil: removeRecipe(recipe)
FileUtil -> recipes.json: writeFile(Path filepath, RecipeLibrary recipeLibrary)
FileUtil -> RecipeFilehandler: true if deleted successfully
RecipeFilehandler -> DirectRecipeHubController: true if deleted successfully

loop profiles.size() times
    RecipeController -> Profile: removeFavorite(Recipe recipe)
    RecipeController -> Profile: removeRecipe(Recipe recipe)
end

RecipeController -> DirectRecipeHubController: "OK-click"
DirectRecipeHubController -> UserFilehandler: saveProfiles(List<Profile> profiles)
UserFilehandler -> FileUtil: writeAllProfiles(List<Profile> profiles)
FileUtil -> userinfo.json: writeFile(Path filepath, List<Profile> profiles)
FileUtil -> UserFilehandler: true if updated successfully
UserFilehandler -> DirectRecipeHubController: true if updated successfully

RecipeController -> MainscreenController: switchSceneMain(actionEvent, "Mainscreen.fxml");
MainscreenController -> User: Shows all recipes to user without the deleted recipe
@enduml
